config/routes.rb
Rails.application.routes.draw do
  get 'logdude/entries/:model_type/:model_id' => 'logdude/entries#index', :as => 'logs_dude',
                                                  :constraints => {:model_type => /\w+/, :model_id => /\d+/}
end

app/controllers/logdude/entries_controller.rb
module Logdude
  class EntriesController < ApplicationController
    def index
      render json: Logdude::Models::Entry.all(params[:model_type], params[:model_id].to_i)
    end
  end
end

app/views/helpers/_show.html.erb
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <td>Model id</td>
    <td>Before</td>
    <td>After</td>
    <td>Changer id</td>
  </tr>
  </thead>
  <tbody id="logsdude">

  </tbody>
</table>

<script>
    window.onload = function() {
        $.ajax({
            url: "<%= logs_dude_path(model_type: model_type, model_id: model_id) %>",
            method: 'GET',
            isArray: true,
            success: function(data) {
                for(var index in data) {
                    var entry = data[index]
                    $("tbody#logsdude").append(
                            "<tr>" +
                            "<td>"+entry['model_id']+"</td>" +
                            "<td>"+JSON.stringify(entry['before'])+"</td>" +
                            "<td>"+JSON.stringify(entry['after'])+"</td>" +
                            "<td>"+entry['user_id']+"</td>" +
                            "</tr>"
                    )
                }
            }
        })
    }
</script>